updatest port forwarding.

diff --git a/media/transmission/transmission.deployment.yml b/media/transmission/transmission.deployment.yml
--- a/media/transmission/transmission.deployment.yml
+++ b/media/transmission/transmission.deployment.yml
@@ -40,7 +40,7 @@ spec:
                   name: transmission
                   key: key
             - name: PROTONVPN_SERVER
-              value: "IS-NL#1"
+              value: "NL#4"
             - name: DEBUG
               value: "0"
             - name: KILL_SWITCH
@@ -51,9 +51,32 @@ spec:
                 - NET_ADMIN
           command: ["/bin/bash", "-c"]
           args:
-            [
-              "/usr/bin/protonwire connect --container & sleep 10; natpmpc -a 1 0 udp 60 -g 10.2.0.1; natpmpc -a 1 0 tcp 60 -g 10.2.0.1 | grep -oP 'public\\ port\\ \\K\\w+' > /config/protonvpn-port; echo \"Port written to protonvpn-port file\"; cat /config/protonvpn-port; while true; do date; natpmpc -a 1 0 udp 60 -g 10.2.0.1 && natpmpc -a 1 0 tcp 60 -g 10.2.0.1 || { echo -e \"ERROR with natpmpc command \\a\"; break; }; sleep 45; done",
-            ]
+            - |
+              /usr/bin/protonwire connect --service --p2p --kill-switch --check-interval 60 &
+              __check_connection() {
+                protonwire healthcheck --silent --service-status-file
+              }
+              __config_and_renew_port_forward() {
+                while true; do
+                  natpmpc -a 1 0 udp 60 -g 10.2.0.1 >/dev/null || {
+                    echo "[ERROR   ][NATPMP] Command natpmpc has failed! Retrying in 3 seconds..."
+                    sleep 3
+                    break
+                  }
+                  natpmpc -a 1 0 tcp 60 -g 10.2.0.1 |
+                    grep -oP 'public\ port\ \K\w+' >/tmp/protonvpn-port-forward.txt
+                  echo "NATPMP_PORT=$(cat /tmp/protonvpn-port-forward.txt)" >/tmp/natpmp.env
+                  echo "[SUCCESS ][NATPMP] Port forward successful! Will renew in 45 seconds..."
+                  echo "[INFO    ][NATPMP] Port forward enabled at port: $(cat /tmp/protonvpn-port-forward.txt)"
+                  sleep 45
+                done
+              }
+              until __check_connection; do
+                echo "[ERROR   ][NATPMP] VPN connection NOT established! Retrying in 10 seconds..."
+                sleep 10
+              done
+              echo "[SUCCESS ][NATPMP] VPN connection established! Configuring it now..."
+              __config_and_renew_port_forward
           ports:
             - containerPort: 8000
           resources:
